---
title: "introR: introdução à linguagem R"
format: pdf
editor: source
---

### Docentes

Prof. Dr. Maurício Humberto Vancine  
Prof. Dr. Mario Moura (responsável)

### Carga horária

30 h (2 créditos)

### Participantes

10 alunos (+ 5 especiais)

### Datas e horários

Teórico-prático: 14/10/2025 a 17/10/2025 (9-17h)

### Repositório da disciplina

<https://github.com/course-intror>

### Resumo

A disciplina tem como foco principal o controle de versão com git/GitHub e a introdução à programação em R, ambos aplicados a dados ecológicos. São abordados os principais aspectos teóricos e práticos do controle de versão, incluindo o uso do software git e de repositórios remotos no GitHub. Além disso, são apresentados os principais tópicos de programação em R, desde recursos do Base R até o tidyverse, com ênfase no manejo e na visualização de dados ecológicos, bem como em tópicos avançados de programação nessa linguagem. Serão abordados os seguintes temas: (1) controle de versão com git e GitHub, (2) introdução à programação em R (Base R), (3) introdução à programação em R (tidyverse), (4) introdução à programação em R (visualização), (5) tópicos avançados em programação no R e (6) reprodutibilidade em R e GitHub. A carga horária total será de 30 horas, onde nos três dias iniciais serão ministrados 20 horas de aulas teórico-práticas. As 10 horas restantes serão direcionadas à formulação e execução de um projeto com dados reais, como forma de avaliação para compor a nota final da disciplina. Ao final da disciplina, os alunos devem ser capazes de utilizar git/GitHub para trabalho colaborativo, e aplicar fundamentos e técnicas avançadas de programação em R para manejo e visualização de dados ecológicos.

### Ementa

A disciplina tem como foco principal o controle de versão com git/GitHub e a introdução à programação em R aplicada a dados ecológicos. São abordados tanto os aspectos teóricos quanto práticos do controle de versão, incluindo o uso do software git e de repositórios remotos no GitHub. Além disso, são apresentados os principais tópicos de programação em R, desde recursos do Base R até o tidyverse, com ênfase no manejo e na visualização de dados ecológicos, bem como em tópicos avançados de programação na linguagem. Por fim, a disciplina tem o objetivo de fomentar a discussão sobre ciência aberta e reprodutibilidade em trabalho científicos.

### Objetivos dos curso

- Apresentar os conceitos e aplicações do controle de versão com git/GitHub, destacando sua importância para o trabalho colaborativo em ciência.
- Explorar aspectos teóricos e práticos do uso do software git e de repositórios remotos no GitHub.
- Introduzir os fundamentos da programação em R, desde os recursos do Base R até o uso do tidyverse.
- Desenvolver habilidades no manejo e visualização de dados ecológicos por meio da linguagem R.
- Abordar tópicos avançados de programação em R (controle de fluxo, repetições e funções), ampliando a capacidade analítica dos participantes.
- Discutir ciência aberta e reprodutibilidade em trabalho científicos.

### Avaliação

Os discentes serão avaliados de forma contínua, considerando sua participação no desenvolvimento coletivo da disciplina, bem como nos debates realizados durante as aulas teóricas e práticas. Além disso, será desenvolvido um projeto prático em grupo, integrando os conteúdos trabalhados ao longo da disciplina, que também servirá como instrumento de avaliação.

### Cronograma

| Dia | Atividade                         | 
|-----|-----------------------------------|
| Dia 01| Boas-vindas e apresentações | 
| Dia 01| Aula teórica 1: controle de versão |
| Dia 01| Aula prática 1: controle de versão |
| Dia 02| Aula teórica 2: introdução à programação em R (Base R)   |
| Dia 02| Aula teórica 3: introdução à programação em R (tidyverse) |
| Dia 02| Aula teórica 4: introdução à programação em R (visualização) |
| Dia 03| Aula teórica 5: tópicos avançados em programação no R |
| Dia 03| Aula teórica 6: reprodutibilidade em R e GitHub |
| Dia 03| Aula prática 2: reprodutibilidade em R e GitHub |
| Dia 04| Projeto prático: desenvolvimento de uma análise ecológica reprodutível |
| Dia 04| Projeto prático: apresentação dos projetos  |
| Dia 04| Discussão: ciência aberta e reprodutibilidade |
| Dia 04| Encerramento |

### Conteúdo

### 1 Controle de versão com git, GitHub e RStudio

1. Conferindo os computadores
1. Controle de versão
1. git e GitHub
1. Detalhes do GitHub
1. Criando um repositório
1. Configuração: git config
1. Controle de versão na prática
1. Iniciando localmente: git init
1. Iniciando remotamente: fork e git clone
1. Versionamento: git status, git add e git commit
1. Ignorando: .gitignore
1. Histórico: git log e git show
1. Diferença: git diff
1. Desfazer: git restore, git revert e git reset
1. Ramificações: git branch, git switch e git merge
1. Remoto: git remote, git push e git pull
1. GitHub: Pull request
1. Conflitos
1. Interface gráfica do RStudio

### 2 Introdução à programação em R (Base R)

1. Linguagem R
1. RStudio
1. Console
1. Scripts
1. Operadores
1. Objetos
1. Funções
1. Pacotes
1. Ajuda
1. Ambiente
1. Citações
1. Principais erros
1. Atributos dos objetos
1. Manipulação de dados unidimensionais
1. Manipulação de dados multidimensionais
1. Valores faltantes e especiais
1. Diretório de trabalho
1. Importar dados
1. Conferência de dados importados
1. Exportar dados

### 3 Introdução à programação em R (tidyverse)

1. Contextualização
1. tidyverse
1. here
1. readr, readxl e writexl
1. tibble
1. magrittr (pipe - %\>%)
1. tidyr
1. dplyr
1. stringr
1. forcats
1. lubridate
1. purrr

### 4 Introdução à programação em R (visualização)

1. Pacotes para produção de gráficos
1. Gramática dos gráficos
1. Principal material de estudo
1. Principais tipos de gráficos
1. Histograma e Densidade
1. Gráfico de setores
1. Gráfico de barras
1. Gráfico de caixas
1. Gráfico de dispersão
1. Gráfico pareado
1. Combinando gráficos
1. Gráficos animados
1. Gráficos interativos
1. Gráficos usando interface

### 5 Tópicos avançados em programação no R

1. Tabelas de frequência
1. Frequência absoluta e relativa
1. Função: table
1. Medidas de posição e dispersão
1. Funções: apply, lapply, sapply, tapply
1. Controle de fluxo
1. Condicional: if, else e else if
1. Estruturas de repetição
1. Laços: for, while e repeat
1. Comandos: break e next
1. Funções
1. Funções externas: source

### 6 Reprodutibilidade em R e GitHub

1. renv
1. quarto
1. quarto: documentos
1. quarto: slides
1. quarto: websites
1. quarto e GitHub

### Referências

Chang W. 2013. R Graphics Cookbook: Practical Recipes for Visualizing Data. 2 ed. O'Reilly Media. <https://r-graphics.org>

Chacon S., Straub B. 2014. Pro Git. 2 ed. Apress. <https://git-scm.com/book/en/v2>

Cotton R. 2013. Learning R: A Step-by-Step Function Guide to Data Analysis. O'Reilly Media.

Davies TM. 2016. The Book of R: A First Course in Programming and Statistics. No Starch Press.

Damiani A, Milz B, Lente C, Falbel D, Correa F, Trecenti J, Luduvice N, Lacerda T, Amorim W. 2025. Ciência de Dados em R. [https://livro.curso-r.com](https://livro.curso-r.com/)

Da Silva FR, Gonçalves-Souza T, Paterno GB, Provete DB, Vancine MH. 2022. Análises Ecológicas no R. Recife: Nupeea. Bauru, SP: Canal 6. <https://analises-ecologicas.com>

Engel C. 2019. Introduction to R. <https://cengel.github.io/R-intro>

Hastle T, Tibshirani R, Friedman J. 2016. The Elements of Statistical Learning: Data Mining, Inference, and Prediction. 2 ed. Springer. <https://web.stanford.edu/~hastie/ElemStatLearn> Healy K. 2019. Data Visualization: a practical introduction. Princeton University Press.

James G, Witten D, Hastie T, Tibshirani R. 2013. An Introduction to Statistical Learning: with Applications in R. 2.ed. Springer. <http://faculty.marshall.usc.edu/gareth-james/ISL>

Kabacoff RI. 2015. R in Action: Data analysis and graphics with R. 2.ed. Manning.

Lander JP. 2017. R for Everyone: Advanced Analytics and Graphics. Addison-Wesley Professional.

Matloff N. 2011. The Art of R Programming: A Tour of Statistical Software Design. No Starch Press.

Oliveira PF, Guerra S, Mcdonnell, R. 2018. Ciência de dados com R – Introdução. IBPAD. <https://cdr.ibpad.com.br>

R Core Team. 2020. R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. <https://www.r-project.org>

Teetor P. 2011. R Cookbook. O'Reilly Media. <http://www.cookbook-r.com>

Wickham H. 2019. Advanced R. 2 ed. Chapman and Hall/CRC. <https://adv-r.hadley.nz>

Wickham H. 2014. Tidy data. Journal of Statistical Software. 59(10): 1-23.

Wickham H, Cetinkaya-Rundel M, Grolemund G. 2023. R for Data Science: Import, Tidy, Transform, Visualize, and Model Data. O'Reilly Media. <https://r4ds.hadley.nz>

Wickham H et al. 2019. Welcome to the Tidyverse. Journal of Open Source Software. 4(43):1686.

Wickham H. 2020. ggplot2: Elegant Graphics for Data Analysis. 3 ed. Springer. <https://ggplot2-book.org>

Wilk CO. 2019. Fundamentals of Data Visualization: A Primer on Making Informative and Compelling Figures. O'Reilly Media. <https://serialmentor.com/dataviz>
